/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiz;

/**
 *
 * @author notebook
 */
public class RegoleDelGioco extends javax.swing.JFrame {

    /**
     * Creates new form RegoleDelGioco
     */
    public RegoleDelGioco() {
        initComponents();
        jLabel1.setText("<html>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam gravida lacus tellus, in aliquet mauris ultrices vitae. Quisque blandit dignissim tortor quis molestie. Suspendisse id dui ultricies, hendrerit elit sed, rhoncus arcu. Etiam aliquam dui non sollicitudin vehicula. Donec vitae erat nisi. Integer ullamcorper ipsum augue, sed elementum ex maximus ac. Phasellus hendrerit tellus vel tincidunt sodales. Sed a semper magna. Phasellus suscipit ullamcorper sapien sed dictum. Fusce vel purus vulputate dui pulvinar sollicitudin. Duis ante ligula, faucibus convallis ante vel, mattis condimentum justo. Etiam eget turpis ornare, faucibus turpis a, aliquet massa.\n" +
"\n" +
"Mauris vestibulum sagittis nisi, tincidunt dapibus risus finibus vitae. Phasellus lacinia ex a metus laoreet ullamcorper. Praesent pharetra eget ante quis malesuada. Cras accumsan aliquet est. Aliquam vel nibh at libero gravida aliquam. Donec at nisl ac erat malesuada accumsan ut a sem. Maecenas vel tellus sed dolor varius vestibulum a vitae quam. Suspendisse at sollicitudin nunc. Quisque sed mi pretium, pulvinar metus a, faucibus libero. Integer aliquet orci sed tellus pharetra, at semper est convallis. In vestibulum, turpis ac tincidunt finibus, velit enim hendrerit nunc, sit amet vestibulum massa ante quis metus. Phasellus porta arcu vel dapibus maximus.\n" +
"\n" +
"Duis semper dictum ex id placerat. Morbi eget lectus non nibh convallis pulvinar "
                + "quis eu est. Etiam sed varius turpis, at aliquam tortor."
                + " Mauris eu ipsum non nunc pretium convallis. Ut sed velit eu mauris blandit aliquam quis ac lectus. Morbi dapibus mauris at mi sollicitudin, eget euismod justo vulputate. Etiam blandit diam ac rhoncus interdum. Nam rutrum quam at est iaculis blandit. Etiam semper bibendum orci nec sodales. Vestibulum porttitor nulla eget arcu pharetra vehicula. Curabitur lacinia mauris velit, eu faucibus eros gravida quis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean scelerisque, lorem in vestibulum ullamcorper, turpis nibh tempor mauris, nec vehicula odio massa eget ante. In ullamcorper molestie arcu, ut ultricies est mollis nec.</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jLabel1.setText("jLabel1");
        jScrollPane1.setViewportView(jLabel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegoleDelGioco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegoleDelGioco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegoleDelGioco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegoleDelGioco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegoleDelGioco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
