/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiz.interfacce;

import guiz.GUIzUtils;
import guiz.RepositoryDomande;
import guiz.SettingsRepository;
import guiz.interfacce.aggiungimodifica.AggiungiModificaUtente;
import guiz.interfacce.partita.domandaChiusa;
import guiz.interfacce.partita.domandaPT;
import guiz.interfacce.partita.domandaTempo;
import guiz.modelli.Domanda;
import guiz.modelli.Domanda.Difficolta;
import guiz.modelli.DomandaATempo;
import guiz.modelli.DomandaChiusa;
import guiz.modelli.DomandaPerdiTutto;
import guiz.modelli.Utente;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 *
 * @author notebook
 */
public class NuovaPartita extends javax.swing.JFrame {

    public NuovaPartita() {     //costruttore
        initComponents();       //inizializza i componenti
        setLocationRelativeTo(null);

        DefaultListModel<String> model = new DefaultListModel<>();
        lstUtenti.setModel(model);
        
        ((DefaultComboBoxModel) cmbDifficolta.getModel()).addElement(Domanda.Difficolta.facile);
        ((DefaultComboBoxModel) cmbDifficolta.getModel()).addElement(Domanda.Difficolta.media);
        ((DefaultComboBoxModel) cmbDifficolta.getModel()).addElement(Domanda.Difficolta.difficile);
        
        if (!SettingsRepository.getInstance().puoScegliereDomandeAPartita())
        {
            cmbDifficolta.setSelectedIndex(1);
            cmbDifficolta.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblDifficolta = new javax.swing.JLabel();
        lblUtenti = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstUtenti = new javax.swing.JList<>();
        btnAggiungi = new javax.swing.JButton();
        btnElimina = new javax.swing.JButton();
        btnModifica = new javax.swing.JButton();
        btnModificaPartita = new javax.swing.JButton();
        cmbDifficolta = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PRE-PARTITA");

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        lblDifficolta.setText("Difficoltà");

        lblUtenti.setText("Utenti");

        lstUtenti.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstUtenti);

        btnAggiungi.setText("+");
        btnAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggiungiActionPerformed(evt);
            }
        });

        btnElimina.setText("-");
        btnElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaActionPerformed(evt);
            }
        });

        btnModifica.setText("Modifica");
        btnModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaActionPerformed(evt);
            }
        });

        btnModificaPartita.setText("Inizia partita");
        btnModificaPartita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaPartitaActionPerformed(evt);
            }
        });

        cmbDifficolta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        cmbDifficolta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDifficoltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDifficolta)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblUtenti)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnAggiungi)
                                .addGap(18, 18, 18)
                                .addComponent(btnElimina)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnModifica)))
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(btnModificaPartita)
                .addGap(0, 164, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbDifficolta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblDifficolta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbDifficolta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUtenti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnElimina)
                        .addComponent(btnModifica))
                    .addComponent(btnAggiungi))
                .addGap(18, 18, 18)
                .addComponent(btnModificaPartita)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggiungiActionPerformed
        new AggiungiModificaUtente(lstUtenti, null).setVisible(true);
    }//GEN-LAST:event_btnAggiungiActionPerformed

    private void btnEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaActionPerformed
        int selectedIndex = lstUtenti.getSelectedIndex();

        if (selectedIndex >= 0) {
            ListModel<String> listModel = lstUtenti.getModel();
            DefaultListModel<String> model = (DefaultListModel<String>) listModel;

            model.remove(selectedIndex);
        }
    }//GEN-LAST:event_btnEliminaActionPerformed

    private void btnModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaActionPerformed
        int selectedIndex = lstUtenti.getSelectedIndex();

        if (selectedIndex >= 0) {
            new AggiungiModificaUtente(lstUtenti, new Utente(lstUtenti.getSelectedValue()), selectedIndex).setVisible(true);
        }
    }//GEN-LAST:event_btnModificaActionPerformed

    private void btnModificaPartitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaPartitaActionPerformed
        ArrayList<Utente> utenti = new ArrayList<>();
        ListModel<String> listModel = lstUtenti.getModel();
        DefaultListModel<String> model = (DefaultListModel<String>) listModel;

        Difficolta difficoltaScelta = Domanda.Difficolta.media;

        if (model.getSize() < 2) {
            return;
        }

        for (int i = 0; i < model.getSize(); i++) {
            utenti.add(new Utente(model.get(i)));
        }
        
        Collections.shuffle(utenti);

        switch (cmbDifficolta.getSelectedIndex()) {
            case 0:
                difficoltaScelta = Domanda.Difficolta.facile;
                break;

            case 1:
                difficoltaScelta = Domanda.Difficolta.media;
                break;

            case 2:
                difficoltaScelta = Domanda.Difficolta.difficile;
                break;
        }

        Integer numeroDiDomande = SettingsRepository.getInstance().domandeAPartita();
        ArrayList<Domanda> tutteLeDomande = RepositoryDomande.getInstance().getDomande();

        ArrayList<Domanda> domandeConsiderate = new ArrayList<>();
        for (Domanda d : tutteLeDomande) {
            if (difficoltaScelta.equals(d.getDifficolta())) {
                domandeConsiderate.add(d);
            }
        }

        if (numeroDiDomande > domandeConsiderate.size()) {
            numeroDiDomande = domandeConsiderate.size();
        }

        Collections.shuffle(domandeConsiderate);
        List<Domanda> domandeEstratte = domandeConsiderate.subList(0, numeroDiDomande);
        
        if (domandeEstratte.size() % 2 != 0) 
        {
            domandeEstratte.remove(0);
            numeroDiDomande--;
        }

        switch (domandeEstratte.get(0).getTipo()) {
            case DomandaATempo.labelTipo:
                new domandaTempo(utenti, domandeEstratte, 0, 0).setVisible(true);
                break;
            case DomandaPerdiTutto.labelTipo:
                new domandaPT(utenti, domandeEstratte, 0, 0).setVisible(true);
                break;
            case DomandaChiusa.labelTipo:
                new domandaChiusa(utenti, domandeEstratte, 0, 0).setVisible(true);
                break;
        }

        this.dispose();
    }//GEN-LAST:event_btnModificaPartitaActionPerformed

    private void cmbDifficoltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDifficoltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDifficoltaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggiungi;
    private javax.swing.JButton btnElimina;
    private javax.swing.JButton btnModifica;
    private javax.swing.JButton btnModificaPartita;
    private javax.swing.JComboBox<String> cmbDifficolta;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDifficolta;
    private javax.swing.JLabel lblUtenti;
    private javax.swing.JList<String> lstUtenti;
    // End of variables declaration//GEN-END:variables
}
