/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiz.interfacce;

import guiz.GUIzUtils;
import guiz.RepositoryDomande;
import guiz.interfacce.aggiungimodifica.AggiungiHub;
import guiz.interfacce.aggiungimodifica.AggiungiModificaDomandaATempo;
import guiz.interfacce.aggiungimodifica.AggiungiModificaDomandaChiusa;
import guiz.interfacce.aggiungimodifica.AggiungiModificaDomandaPerdiTutto;
import guiz.modelli.Domanda;
import guiz.modelli.DomandaATempo;
import guiz.modelli.DomandaChiusa;
import guiz.modelli.DomandaPerdiTutto;
import guiz.modelli.OpzioneDomandaChiusa;
import java.time.Duration;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author notebook
 */
public class PannelloDiAmministrazione extends javax.swing.JFrame {

    public final static int INDICE_TABELLA_ID = 0;
    public final static int INDICE_TABELLA_TESTO = 1;
    public final static int INDICE_TABELLA_TIPO = 2;
    public final static int INDICE_TABELLA_RISPOSTA = 3;
    public final static int INDICE_TABELLA_OPZIONI = 4;
    public final static int INDICE_TABELLA_TEMPO = 5;

    private void initTableRowCount(int count) {
        DefaultTableModel model = (DefaultTableModel) tblDomande.getModel();
        model.setRowCount(count);
        tblDomande.setModel(model);
    }

    private void initTabella() {
        ArrayList<Domanda> domande = RepositoryDomande.getInstance().getDomande();

        initTableRowCount(domande.size());

        int riga = 0;
        for (Domanda d : domande) {
            tblDomande.getModel().setValueAt(d.getId(), riga, INDICE_TABELLA_ID);
            tblDomande.getModel().setValueAt(d.getTesto(), riga, INDICE_TABELLA_TESTO);
            tblDomande.getModel().setValueAt(d.getTipo(), riga, INDICE_TABELLA_TIPO);
            
            if (d instanceof DomandaChiusa) {
                DomandaChiusa dc = (DomandaChiusa) d;
                

                tblDomande.getModel().setValueAt(GUIzUtils.formatOpzioni(dc.getOpzioni()), riga, INDICE_TABELLA_OPZIONI);
            }

            if (d instanceof DomandaPerdiTutto) {
                DomandaPerdiTutto dpt = (DomandaPerdiTutto) d;
                tblDomande.getModel().setValueAt(dpt.getRisposta(), riga, INDICE_TABELLA_RISPOSTA);
            }

            if (d instanceof DomandaATempo) {
                DomandaATempo dt = (DomandaATempo) d;
                tblDomande.getModel().setValueAt(dt.getRisposta(), riga, INDICE_TABELLA_RISPOSTA);
                long durataSecondi = dt.getTempo().toMillis() / 1000;
                tblDomande.getModel().setValueAt(durataSecondi + " second" + (durataSecondi > 1 ? "i" : "o"), riga, INDICE_TABELLA_TEMPO);
            }

            riga++;
        }
    }

    public PannelloDiAmministrazione() {
        initComponents();
        initTabella();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDomande = new javax.swing.JTable();
        cmbOpzioni = new javax.swing.JComboBox<>();
        btnModifica = new javax.swing.JButton();
        lblImporta = new javax.swing.JLabel();
        btnImporta = new javax.swing.JButton();
        chbDifficolta = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        lblNumeroDomande = new javax.swing.JLabel();
        btnSalva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblDomande.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Testo", "Tipo", "Risposta", "Opzioni", "Tempo",
            }
        ));
        jScrollPane1.setViewportView(tblDomande);

        cmbOpzioni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cancella", "Aggiungi", "Esporta" }));
        cmbOpzioni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOpzioniActionPerformed(evt);
            }
        });

        btnModifica.setText("Modifica");
        btnModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaActionPerformed(evt);
            }
        });

        lblImporta.setText("Importa domande da file esterno");

        btnImporta.setText("Importa");

        chbDifficolta.setText("Permetti all'utente di selezionare il livello di difficoltà");

        lblNumeroDomande.setText("Domande a partita");

        btnSalva.setText("Salva");
        btnSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnModifica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbOpzioni, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbDifficolta)
                            .addComponent(lblImporta)
                            .addComponent(btnImporta)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumeroDomande)
                            .addComponent(btnSalva))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbOpzioni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifica))
                .addGap(33, 33, 33)
                .addComponent(lblImporta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImporta)
                .addGap(18, 18, 18)
                .addComponent(chbDifficolta)
                .addGap(18, 18, 18)
                .addComponent(lblNumeroDomande)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalva)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbOpzioniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOpzioniActionPerformed
        switch(cmbOpzioni.getSelectedItem().toString()){
            case "Aggiungi":
                new AggiungiHub(tblDomande).setVisible(true);
                break;
                
            case "Cancella":
                int selectedRow = tblDomande.getSelectedRow();
                if (selectedRow >= 0){
                    RepositoryDomande.getInstance().rimuoviDomanda(RepositoryDomande.getInstance().getDomande().get(selectedRow));
                    
                    DefaultTableModel model = (DefaultTableModel) tblDomande.getModel();
                    model.removeRow(selectedRow);
                    tblDomande.setModel(model);
                }
                break;
        }
    }//GEN-LAST:event_cmbOpzioniActionPerformed

    private void btnModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaActionPerformed
        int selectedRow = tblDomande.getSelectedRow();
        TableModel model = tblDomande.getModel();
        
        if (selectedRow >= 0) {
            int idDomanda = Integer.parseInt(model.getValueAt(selectedRow, INDICE_TABELLA_ID).toString());
            switch (model.getValueAt(selectedRow, INDICE_TABELLA_TIPO).toString()) {
                case DomandaChiusa.labelTipo:
                    DomandaChiusa domandaChiusa = (DomandaChiusa) RepositoryDomande.getInstance().getDomandaWhereIdIs(idDomanda);
                    new AggiungiModificaDomandaChiusa(domandaChiusa, tblDomande, selectedRow).setVisible(true);
                    break;
                case DomandaPerdiTutto.labelTipo:
                    DomandaPerdiTutto domandaPerdiTutto = (DomandaPerdiTutto) RepositoryDomande.getInstance().getDomandaWhereIdIs(idDomanda);
                    new AggiungiModificaDomandaPerdiTutto(domandaPerdiTutto, tblDomande, selectedRow).setVisible(true);
                    break;
                case DomandaATempo.labelTipo:
                    DomandaATempo domandaATempo = (DomandaATempo) RepositoryDomande.getInstance().getDomandaWhereIdIs(idDomanda);
                    new AggiungiModificaDomandaATempo(domandaATempo, tblDomande, selectedRow).setVisible(true);
                    break;
            }
        }
    }//GEN-LAST:event_btnModificaActionPerformed

    private void btnSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PannelloDiAmministrazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PannelloDiAmministrazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PannelloDiAmministrazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PannelloDiAmministrazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PannelloDiAmministrazione().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImporta;
    private javax.swing.JButton btnModifica;
    private javax.swing.JButton btnSalva;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chbDifficolta;
    private javax.swing.JComboBox<String> cmbOpzioni;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblImporta;
    private javax.swing.JLabel lblNumeroDomande;
    private javax.swing.JTable tblDomande;
    // End of variables declaration//GEN-END:variables
}
