/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiz.interfacce.partita;

import guiz.GUIzUtils;
import guiz.modelli.Utente;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daniele
 */
public class ReportFinePartita extends javax.swing.JFrame {

    List<Utente> utenti;

    /**
     * Creates new form ReportPartita
     */
    private ReportFinePartita() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public ReportFinePartita(List<Utente> utenti) {
        this();
        this.utenti = utenti;

        this.utenti = GUIzUtils.orderByPoints(utenti);
        String[] values = new String[3];
        int i = 1;
        for (Utente u : this.utenti) {
            values[0] = String.valueOf(i);
            values[1] = u.getNome();
            values[2] = String.valueOf(u.getPunteggio());

            ((DefaultTableModel) tlbClassifica.getModel()).addRow(values);
            i++;
        }
        
        if (this.utenti.get(0).getPunteggio() > this.utenti.get(1).getPunteggio())
            lblVincitore.setText("Complimenti " + this.utenti.get(0).getNome() + ": hai vinto!");
        else
        {
            StringBuilder builder = new StringBuilder("Pareggio tra ");
            
            for (int j = 0; j < this.utenti.size() - 1 && this.utenti.get(j).getPunteggio() == this.utenti.get(j + 1).getPunteggio(); j += 2)
                builder.append(this.utenti.get(j).getNome()).append(", ").append(this.utenti.get(j + 1).getNome()).append(", ");
            
            if (this.utenti.get(this.utenti.size() - 1).getPunteggio() == this.utenti.get(this.utenti.size() - 2).getPunteggio())
                builder.append(this.utenti.get(this.utenti.size() - 1).getNome());
            else{
                builder.deleteCharAt(builder.length() - 1);
                builder.deleteCharAt(builder.length() - 1);
            }
            lblVincitore.setText(builder.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tlbClassifica = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblVincitore = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PUNTEGGI");

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        tlbClassifica.setBackground(new java.awt.Color(204, 204, 255));
        tlbClassifica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Posizione", "Giocatore", "Punteggio"
            }
        ));
        jScrollPane1.setViewportView(tlbClassifica);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setText("FINE PARTITA!");

        lblVincitore.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblVincitore.setText("Complimenti : hai vinto!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(89, 89, 89))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVincitore)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(lblVincitore)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblVincitore;
    private javax.swing.JTable tlbClassifica;
    // End of variables declaration//GEN-END:variables
}
