/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiz.interfacce.partita;

import guiz.GUIzUtils;
import guiz.modelli.Utente;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daniele
 */
public class ReportFinePartita extends javax.swing.JFrame {

    List<Utente> utenti;

    /**
     * Creates new form ReportPartita
     */
    private ReportFinePartita() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public ReportFinePartita(List<Utente> utenti) {
        this();
        this.utenti = utenti;

        this.utenti = GUIzUtils.orderByPoints(utenti);
        String[] values = new String[3];
        int i = 1;
        for (Utente u : this.utenti) {
            values[0] = String.valueOf(i);
            values[1] = u.getNome();
            values[2] = String.valueOf(u.getPunteggio());

            ((DefaultTableModel) tlbClassifica.getModel()).addRow(values);
            i++;
        }
        
        if (this.utenti.get(0).getPunteggio() > this.utenti.get(1).getPunteggio())
            lblVincitore.setText("Complimenti " + this.utenti.get(0).getNome() + ": hai vinto!");
        else
        {
            StringBuilder builder = new StringBuilder("Pareggio tra ");
            int j = 0;
            while (j < this.utenti.size() && this.utenti.get(j).getPunteggio() == this.utenti.get(j + 1).getPunteggio()){
                builder.append(this.utenti.get(j).getNome()).append(", ").append(this.utenti.get(j + 1).getNome()).append(", ");
                j += 2;
            }
            
            builder.deleteCharAt(builder.length() - 1);
            builder.deleteCharAt(builder.length() - 1);
            lblVincitore.setText(builder.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tlbClassifica = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblVincitore = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tlbClassifica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Posizione", "Giocatore", "Punteggio"
            }
        ));
        jScrollPane1.setViewportView(tlbClassifica);

        jLabel2.setText("FINE PARTITA!");

        jLabel3.setText("Classifica");

        lblVincitore.setText("Complimenti Dio Sgangherato: hai vinto!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(201, 201, 201))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(lblVincitore)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblVincitore)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblVincitore;
    private javax.swing.JTable tlbClassifica;
    // End of variables declaration//GEN-END:variables
}
